# Generated by Django 2.2.7 on 2020-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealist',
            name='area_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
