# Generated by Django 2.2.7 on 2020-06-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlist',
            old_name='std_id',
            new_name='roll',
        ),
    ]
